name: CI
on: [push]
jobs:
    phpcs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: bin/ci/phpcs

    phpstan:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [--php=7.4, --php=8.0]
        steps:
            - uses: actions/checkout@v2
            - uses: ./.github/actions/ci-env
            - run: bin/ci/phpstan ${{ matrix.php }}

    phpdd:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: ./.github/actions/ci-env
            - run: bin/ci/phpdd

    composer-normalize:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: bin/ci/composer-normalize --dry-run

#    https://github.com/php-pp/core/issues/1
#    composer-require-checker:
#        runs-on: ubuntu-latest
#        steps:
#            - uses: actions/checkout@v2
#            - uses: ./.github/actions/ci-env
#            - run: bin/ci/composer-require-checker

    composer-validate:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: bin/ci/composer-validate

    shellcheck:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: bin/ci/shellcheck

    unused-scanner:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: bin/ci/unused-scanner

    phpunit:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [--php=7.4, --php=8.0]
        steps:
            - uses: actions/checkout@v2
            - uses: ./.github/actions/ci-env
            - run: bin/ci/phpunit ${{ matrix.php }}
